### ISSUE TITLE
PathNotFoundException: Doesn't draw diagrams on macos

### ISSUE THREAD

**Issue by tieorange** [albemala/dart-lens-app#1]
1. Run dart-lense-app
2. Select Flutter project (has android and web-only support in my case) - it's inside of `/Volumes/Macintosh HD/Users/user/Documents/FlutterProjects/Project-name`
3. No diagram is drawn

```
flutter: [exception: PathNotFoundException(path=/usr/local/bin/cache/dart-sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:159:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:505:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:404:18)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:192:21)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:104:15)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:95:36)
#6      getProjectStructure (package:dart_lens/functions/project-structure.dart:29:22)
<asynchronous suspension>
#7      _RemoteRunner._run (dart:isolate:956:18)
<asynchronous suspension>
]
flutter: [exception: PathNotFoundException(path=/usr/local/bin/cache/dart-sdk/lib/_internal/libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:159:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:505:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:404:18)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:192:21)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:104:15)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:95:36)
#6      getProjectStructure (package:dart_lens/functions/project-structure.dart:29:22)
<asynchronous suspension>
#7      _RemoteRunner._run (dart:isolate:956:18)
<asynchronous suspension>
]
```

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/3984517/224125503-75199eb8-ab9c-4831-a275-3de312a63868.png">

p.s Great project - I love the concept

**Comment by albemala** [comment]
hey @tieorange , thanks for reporting this issue!

could you please run `which dart` on the terminal and post here the result?

there is some code in the app under `project-structure.dart:29` that tries to detect where the dart sdk is installed, but I guess it's failing

also, could you post the output of `flutter doctor`? 

thanks!

**Comment by kuroodo** [comment]
I am having possibly the same issue, but I don't have an exception. I am on Windows 10. I did some digging and found that the issue might be in `project-structure.dart` as you suggested.
`final whichDart = await Process.run('which', ['dart']);` doesn't work for me and never completes. When I set `runInShell` to true it does complete but with an error visible through the `whichDart.stderr` output, which is that `which` isn't a command. This is because in windows the command is `where`. Now it completes without an error, but the issue now is that `where` outputs the following:
```
C:\...\flutter\bin\dart
C:\...\flutter\bin\dart.bat
```
Two strings that point to the dart files in the bin folder. This causes line 27 to not set up the sdk path properly.
When I give it a literal path, everything runs no problem. So it's likely that the fault lies in lines 25 and 27.

Here is my flutter doctor. Ignore that Android Studio error/warning
> Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19044.2604], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.0)
[√] Android Studio (version 2021.2)
[!] Android Studio (version 4.1)
    X Unable to determine bundled Java version.
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.76.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by tieorange** [comment]
@albemala Alright, here you go:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/3984517/224750057-d6b37007-3bf1-4ca8-8cf2-b9b0cf458a1b.png">

Hmm, what if I'll just hardcode the dart path inside the codebase? Might fix it

flutter doctor:
```
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-x64, locale en-UA)
    • Flutter version 3.7.5 on channel stable at /usr/local/Caskroom/flutter/3.3.8/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (3 weeks ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/anduser/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /usr/local/Cellar/openjdk/19.0.2/libexec/openjdk.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 19.0.2)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/anduser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/anduser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Users/anduser/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.8214.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Users/anduser/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.8617.56/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

**Comment by albemala** [comment]
@kuroodo @tieorange thank you both for your replies and insights! @kuroodo yes, you are on the right track.

I'm working on a new version where I've fixed this issue (hopefully). I'll let you know when I'll publish it.

In the meantime you can hard-code the path, yes. File `project-structure.dart`, line 22 I believe. You can change `final dartSdkPath = ...`. Since you both have Flutter installed, it should be `/path/to/flutter/bin/cache/dart-sdk`

**Comment by tieorange** [comment]
Thanks a lot, @albemala! 
Oh hardcoding the path has fixed the issue for me 
`final dartSdkPath = path.normalize('/usr/local/Caskroom/flutter/3.3.8/flutter/bin/cache/dart-sdk');`

You can reproduce this issue by installing Flutter with a Brew instead of manually: https://formulae.brew.sh/cask/flutter

**Comment by albemala** [comment]
@tieorange @kuroodo please pull the latest `main` branch and try again with the latest version (1.1.0). I've changed how the Dart SDK path gets found. Please let me know if it works now or if you still have issue!
