### ISSUE TITLE
Unable to load project

### ISSUE THREAD

**Issue by MarkOSullivan94** [albemala/dart-lens-app#7]
Hi @albemala 👋 

Thought this project was super cool and wanted to give it a try but unfortunately I've had no joy in getting it to load a test project.

I've attached a video of what happens when I hit the refresh button, hope this helps you identify the issue I'm having.

https://github.com/albemala/dart-lens-app/assets/6950843/6a8b029d-f297-441e-b17b-4476db4c43f8

**Comment by albemala** [comment]
hey @MarkOSullivan94 , thanks for reporting this issue. I'm not sure what's going on, would you mind checking from the macOS Console app if you get any error? or worst case, cloning the repo and running in debug?

**Comment by malaschitz** [comment]
The same issue. Output from console:
```

flutter: /Users/rio/Library/Application Support/app.dartlens
flutter: Exploring packages at /Volumes/Macintosh HD/Users/rio/Dropbox/x-projekty/skdps/dpsf
flutter: FormatException: Unexpected end of input (at character 1)

^

flutter: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      getOutdatedPackages (package:dart_lens/functions/outdated-packages.dart:20:35)
<asynchronous suspension>
#7      getPackages (package:dart_lens/functions/project-packages-analysis.dart:25:28)
<asynchronous suspension>
#8      _RemoteRunner._run (dart:isolate:1023:18)
<asynchronous suspension>

```

**Comment by Pavel-dnipro** [comment]
have the same output to console and downloaded macOS app also did not open any project
<img width="978" alt="Знімок екрана 2023-09-28 о 15 49 48" src="https://github.com/albemala/dart-lens-app/assets/56679738/eeffb89f-9aa2-443c-afc1-1af9aa06c6ed">

**Comment by albemala** [comment]
Okay, I actually had the same problem a few times but when refreshing with the arrow button, or closing and reopening the app, it did work fine.

@malaschitz @Pavel-dnipro could you please try closing and reopening the app? Does it work or you still get the same error? Also, do you get the same error when opening other projects?

**Comment by JgomesAT** [comment]
I have the same problem in mac os Sonora

**Comment by ngthailam** [comment]
@albemala 
Mac M1 Venture 13.2.1 here:
while debugging my path is `/Volumes/Macintosh HD/Users/lam/Code/FlutterProjects/galaxy_animation`
and it throws the same exception.

If i hardcode it into `/Users/lam/Code/FlutterProjects/galaxy_animation` 
then it works fine.

Let me also try to fix this problem XD

**Comment by JgomesAT** [comment]
Is there any new?? in Apple Mac is not working
